/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Module;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author JayJomJohn
 */
public class Login extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    int ctr = 0;
    public Login() {
        initComponents();
        conn=JavaConnector.ConnectDb();
        label_username.setVisible(false);
        label_password.setVisible(false); 
        jLabel7.setVisible(false);
        jLabel5.setVisible(false);
        
        showPlaceHolder();
        showIcon();
    }
    
    //DISPLAY ICON
    private void showIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/IconB/sale.png")));
    } 
    //PLACEHOLDER    
    private void showPlaceHolder(){
     txt_password.setEchoChar((char)0);
     txt_password.setText("Password ");
     txt_password.setForeground(Color.GRAY);
     txt_username.setText("Username ");
     txt_username.setForeground(Color.GRAY);
     txt_username.requestDefaultFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelleft = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        label_icon = new javax.swing.JLabel();
        label_type = new javax.swing.JLabel();
        cardpanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        panelRound = new LIB.JPanelRound();
        btn_login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_username = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txt_password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        label_password = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelleft.setBackground(new java.awt.Color(0, 204, 204));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Inventory Management System");

        label_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_manager_127px_1.png"))); // NOI18N

        label_type.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_type.setForeground(new java.awt.Color(255, 255, 255));
        label_type.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelleftLayout = new javax.swing.GroupLayout(panelleft);
        panelleft.setLayout(panelleftLayout);
        panelleftLayout.setHorizontalGroup(
            panelleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelleftLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelleftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_icon, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(label_type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(106, 106, 106))
        );
        panelleftLayout.setVerticalGroup(
            panelleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelleftLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(label_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_type, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        getContentPane().add(panelleft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 580));

        cardpanel.setBackground(new java.awt.Color(36, 47, 65));
        cardpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Sign in");
        cardpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 72, -1, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconA/icons8_user_male_circle_35px.png"))); // NOI18N
        cardpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 144, 50, 50));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconA/icons8_password_35px.png"))); // NOI18N
        cardpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 252, 50, 50));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        cardpanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 300, 250, 10));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show password");
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox1.setFocusPainted(false);
        jCheckBox1.setOpaque(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        cardpanel.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 336, 190, 20));

        panelRound.setBackground(new java.awt.Color(0, 204, 204));
        panelRound.setColorPrimario(new java.awt.Color(0, 255, 255));
        panelRound.setColorSecundario(new java.awt.Color(0, 204, 204));
        panelRound.setLayout(new java.awt.GridBagLayout());

        btn_login.setBackground(new java.awt.Color(0, 102, 102));
        btn_login.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Sign In");
        btn_login.setBorderPainted(false);
        btn_login.setContentAreaFilled(false);
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.setFocusPainted(false);
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_loginMouseExited(evt);
            }
        });
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 135;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelRound.add(btn_login, gridBagConstraints);

        cardpanel.add(panelRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 372, 264, 60));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Already a member ?");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cardpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 444, 252, 30));

        jSeparator3.setBackground(new java.awt.Color(102, 102, 102));
        cardpanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 480, 252, 12));

        txt_username.setBackground(new java.awt.Color(36, 47, 65));
        txt_username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_username.setBorder(null);
        txt_username.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernameFocusGained(evt);
            }
        });
        txt_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_usernameMouseClicked(evt);
            }
        });
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_usernameKeyReleased(evt);
            }
        });
        cardpanel.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 144, 252, 48));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        cardpanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 192, 252, 12));

        txt_password.setBackground(new java.awt.Color(36, 47, 65));
        txt_password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_password.setBorder(null);
        txt_password.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passwordFocusGained(evt);
            }
        });
        txt_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_passwordMouseClicked(evt);
            }
        });
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_passwordKeyReleased(evt);
            }
        });
        cardpanel.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 252, 252, 48));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("PASSWORD");
        cardpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 228, 252, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("USERNAME");
        cardpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 120, 252, -1));

        label_username.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        label_username.setForeground(new java.awt.Color(153, 0, 0));
        label_username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_username.setText("* please enter username");
        cardpanel.add(label_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 204, 252, -1));

        label_password.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        label_password.setForeground(new java.awt.Color(153, 0, 0));
        label_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_password.setText("* please enter password");
        cardpanel.add(label_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 312, 252, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconB/icons8_minimize_window_25px.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        cardpanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 40, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconB/icons8_close_window_25px_1.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        cardpanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 10, 30, 40));

        getContentPane().add(cardpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 440, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()){
            txt_password.setEchoChar((char)0);
        }else{
            txt_password.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btn_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseEntered
        btn_login.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        panelRound.setColorPrimario(new Color(230,230,240));
        panelRound.setBackground(new Color(230,230,240));
    }//GEN-LAST:event_btn_loginMouseEntered

    private void btn_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseExited
        btn_login.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelRound.setColorPrimario(new java.awt.Color(0,255,255));
        panelRound.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_btn_loginMouseExited

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        if(txt_username.getText().equals("")){
            label_username.setVisible(true);
        }else if(txt_password.getText().equals("")){
            label_password.setVisible(true);
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"Complete Your Login Information","Missing Information",2);
        }else{

            try {
                String sql = "SELECT * FROM login WHERE username='"+txt_username.getText()+"' AND password='"+txt_password.getText()+"' ";
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                if(rs.next()){
                    Main m = new Main();
                    if(m.label_user.getText().equals("ADMINISTRATOR")){
                        this.dispose();
                        m.setVisible(true);
                        String a = rs.getString("username");
                        m.label_user.setText(a);


                    }else{
                        this.dispose();
                        m.setVisible(true);
                        String a = rs.getString("username");
                        m.label_user.setText(a);
 
                    }

                }else{
                    JOptionPane.showMessageDialog(null, "Access Denied!:\nInvalid Username or Password");
                    getToolkit().beep();
                    ctr += 1;
                }

                if (ctr == 3) {
                    JOptionPane.showMessageDialog(null, "The Program is now closing ..");
                    this.dispose();
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage(),"Error",2);
            }

        }

    }//GEN-LAST:event_btn_loginActionPerformed

    private void txt_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusGained
        jSeparator1.setBackground(new Color(0,204,204));
        jSeparator2.setBackground(new Color(102,102,102));
        jLabel7.setVisible(true);
    }//GEN-LAST:event_txt_usernameFocusGained

    private void txt_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usernameMouseClicked
        if(txt_username.getForeground().equals(Color.GRAY)){
            txt_username.setText("");
            txt_username.setForeground(Color.white);

        }
    }//GEN-LAST:event_txt_usernameMouseClicked

    private void txt_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyReleased
        if(txt_username.getForeground().equals(Color.GRAY)){
            char idd = txt_username.getText().charAt(0);
            txt_username.setText("");
            txt_username.setText(String.valueOf(idd));
            txt_username.setForeground(Color.white);
        }
    }//GEN-LAST:event_txt_usernameKeyReleased

    private void txt_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusGained
        jSeparator2.setBackground(new Color(0,204,204));
        jSeparator1.setBackground(new Color(102,102,102));
        jLabel5.setVisible(true);
    }//GEN-LAST:event_txt_passwordFocusGained

    private void txt_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passwordMouseClicked
        if(txt_password.getForeground().equals(Color.GRAY)){
            txt_password.setText("");
            txt_password.setForeground(Color.white);
            txt_password.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_txt_passwordMouseClicked

    private void txt_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyReleased
        if(txt_password.getForeground().equals(Color.GRAY)){
            char pass = txt_password.getText().charAt(0);
            txt_password.setText("");//
            txt_password.setText(String.valueOf(pass));
            txt_password.setForeground(Color.white);
            txt_password.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_txt_passwordKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JPanel cardpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel label_icon;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_type;
    private javax.swing.JLabel label_username;
    private LIB.JPanelRound panelRound;
    private javax.swing.JPanel panelleft;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
